foodExpense = int(input("Enter your food exense: "))
travelExpense = int(input("Enter your travel expense: "))
studyExpense = int(input("Enter your study expense: "))
totalExpense = foodExpense+travelExpense+studyExpense
print("\n")
print("====================================")
print("            Expense Tracker         ")
print("====================================")
print("\n")
print(f"Food Expense : {foodExpense}")
print(f"Traverl Expense : {travelExpense}")
print(f"Study Expense : {studyExpense}")
print("\n")
print(f"Total Expense : {totalExpense}")
print("\n")
print("===================================")
