name = input("Enter your name: ")
age =  int(input("Enter your age: "))
college = input("Enter your college name: ")
branch = input("Enter your department / branh: ")
print("\n")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"College: {college}")
print(f"Branch: {branch}")